### PR TITLE
Fix typo in German localization

### PR DESCRIPTION
**Pull request by Skorfulose**
Remove superfluous "t" at the end of the string.

### CODE REVIEW

**Comment by TomBrien** [comment]
Thanks for spotting this, translations are handled on [lokalise.com](https://lokalise.com/project/834452985a05254348aee2.46389241). 

@olbjan I believe this is a duplicate of #476, can you check that’s it’s addressed on lokaise and just waiting a new build? Thanks

**Comment by olbjan** [comment]
It's already fixed in lokalise and the bundle has been refreshed and published.

**Comment by Skorfulose** [comment]
Okay, I was thinking something like that. But README.md and CONTRIBUTING.md and didn‘t give a hint. Since @tefinger and I ran into the same, I suggest I can add a note to CONTRIBUTING.md?

**Comment by TomBrien** [comment]
@Skorfulose I agree entirely. I've just put in a PR (#534) to update those two files. Hopefully it can be merged soon

**Pull request closed without merging**
