### PR TITLE
Only ask to re-enable permissions the first time after they are disabled

### LINKED ISSUE #177: "Allow Motion" Popup keeps re-appearing
Version 1.5.0 (31)
Every time I start the iOS app since the beginning of the beta I have been getting this Allow Motion popup. I do not use any location features of the Home Assistant app so I have everything disabled. But when I click deny in this popup it does not seem to save my choice after restarting the app
image

### PR DESCRIPTION
**Pull request by amelchio**
I think this is closer to what we discussed in Discord: permissions are now only ensured if the status has changed. So the popups should only show when permissions have just been revoked.

Fixes #177

### CODE REVIEW

**Comment by h4nc** [comment]
Do we Need or update the iOS App for that and if yes when will we get this update?

**Comment by robbiet480** [comment]
@h4nc This will be in 1.5.1 which I am planning to submit no later than Friday.

**Comment by h4nc** [comment]
Thanks

**Comment by melikyuksel** [comment]
Is 1.5.1 coming at some point? Two months and counting.

**Pull request merged**
