### PR TITLE
iOS 12

### PR DESCRIPTION
**Pull request by robbiet480**
Had to start fresh from #115 because of how hard @blackgold9 has been killing it with auth API lately, making a merge impossible

---

As outlined [on the forums](https://community.home-assistant.io/t/ios-12-and-saying-goodbye-to-an-old-friend/55720) this PR contains iOS 12 specific changes:

- [x] Remove iOS 9 support
  - [x] Remove UIApplication notification support
- [x] Update deps
- [x] Swift ~~4.2~~ 5 migration
- [x] `mobile_app` integration
- [x] Remove legacy API password support
- [x] [Notification enhancements](https://www.captechconsulting.com/blogs/clean-up-your-lock-screen-3-updates-to-user-notifications-management)
  - [x] Critical Alerts
    - [x] Code added
    - [x] Entitlement Requested
    - [x] Entitlement Received
  - [x] Notification Settings deep link
  - [x] Notification grouping enhancements (set thread ID on every notification generated by the app for native grouping, leave other groups up to users)
  - [x] [Duplicate categories](https://github.com/home-assistant/home-assistant-iOS/issues/64)
  - [x] Actionable notification configuration in-app
- [x] Siri Shortcuts
  - [x] Send Location
	- [x] Default behavior is send current location
	- [x] Check pasteboard for lat,long or address to geocode
  - [x] Call Service
	- [x] Allow setting just service name or service name + payload
	- [x] If no payload set use pasteboard contents
  - [x] Fire Event
	- [x] Allow setting event name or event name + payload
  - [x] Get image from camera proxy
	- [x] Put it on pasteboard
  - [x] Render template
- [x] Apple Watch
  - [ ] Complications support
  - [x] App for actions
  - [x] Watch can make API requests natively
  - [x] Map and Camera interactive notifications
- [x] Today widget
  - [x] Allow calling same actions as Watch
- [x] New data in updates
  - [x] [Pedometer data](https://github.com/home-assistant/home-assistant-iOS/issues/85#issuecomment-466861626)
  - [x] Connection information including SSID, BSSID and connection type
  - [x] Geocoded placemark
  - [x] Timezone
- [x] [Theme support](https://github.com/home-assistant/home-assistant-iOS/issues/219)
- [x] [X-Callback-URL](http://x-callback-url.com/)
	- [x] Expose services for other apps
	- [x] Support a Shortcut payload in notifications to open a shortcut and report back status [see also](https://github.com/home-assistant/home-assistant-iOS/issues/191)
- [x] [Alternate icons](https://github.com/home-assistant/home-assistant-iOS/issues/183)
- [x] Localization updates
  - [x] Uploaded to Lokalise
  - [x] All strings updated as needed
    - [x] Siri Intent Definition File
- [x] Documentation
  - [x] Siri Shortcuts
    - [ ] Examples
  - [ ] Notifications
    - [x] [`thread-id` behavior](https://github.com/home-assistant/home-assistant.io/pull/6410)
    - [x] Critical alerts sound, volume level, etc

### CODE REVIEW

**Comment by robbiet480** [comment]
Putting this here since it's now the 4th time i'm submitting for the critical alerts entitlement and don't want to write it again.

```
Home Assistant for iOS is the companion app to Home Assistant, a open source home automation that puts local control and privacy first. Its primary functions are providing location updates to Home Assistant and allowing users to send rich push notifications from Home Assistant to their devices.
```

```
The app doesn't send any notifications on its own. Users are entirely in control of what notifications are sent, when they are sent, and what they contain. It will be up to the users to decide if they should send a notification as a critical alert. Some examples of critical alerts that users may set up are the garage door being left open after they are detected as in bed or a glass break sensor detecting a intrusion.
```

```
Home Assistant powers peoples homes and keeps them safe and secure. Users need to be able to get critical and timely alerts for things like water leaks or unexpected motion. It will be entirely up to the end users discretion on when to use critical alerts.
```

**Comment by homeassistant** [comment]
Hello @robbiet480,

When attempting to inspect the commits of your pull request for CLA signature status among all authors we encountered commit(s) which were not linked to a GitHub account, thus not allowing us to determine their status(es).

The commits that are missing a linked GitHub account are the following:

- [`dee2fcb7566cc15a9f75d6279d8ce3ea607981a8`](https:&#x2F;&#x2F;github.com&#x2F;home-assistant&#x2F;home-assistant-iOS&#x2F;pull&#x2F;153&#x2F;commits&#x2F;dee2fcb7566cc15a9f75d6279d8ce3ea607981a8) - This commit has something that looks like an email address (travis@travis-ci.org). Maybe try linking that to GitHub?.

Unfortunately, **we are unable to accept this pull request until this situation is corrected.**

Here are your options:

1. If you had an email address set for the commit that simply wasn't linked to your GitHub account you can link that email now and it will retroactively apply to your commits. The simplest way to do this is to click the link to one of the above commits and look for a blue question mark in a blue circle in the top left. Hovering over that bubble will show you what email address you used. Clicking on that button will take you to your email address settings on GitHub. Just add the email address on that page and you're all set. GitHub has more information about this option [in their help center](https://help.github.com/articles/setting-your-email-in-git/#commits-on-github-arent-linking-to-my-account).

2. If you didn't use an email address at all, it was an invalid email, or it's one you can't link to your GitHub, you will need to change the authorship information of the commit and your global Git settings so this doesn't happen again going forward. GitHub provides some great instructions on how to change your authorship information [in their help center](https://help.github.com/articles/setting-your-email-in-git/).
   * If you only made a single commit you should be able to run
      ```
      git commit --amend --author="Author Name <email@address.com>"
      ```
      (substituting Author Name and email@address.com for your actual information) to set the authorship information.
   * If you made more than one commit and the commit with the missing authorship information is not the most recent one you have two options:
       1. You can re-create all commits missing authorship information. This is going to be the easiest solution for developers that aren't extremely confident in their Git and command line skills.
       2. You can use [this script](https://help.github.com/articles/changing-author-info/) that GitHub provides to rewrite history. **Please note:** this should be used only if you are very confident in your abilities and understand its impacts.
   * Whichever method you choose, I will come by to re-check the pull request once you push the fixes to this branch.

We apologize for this inconvenience, especially since it usually bites new contributors to Home Assistant. We hope you understand the need for us to protect ourselves and the great community we all have built legally. The best thing to come out of this is that you only need to fix this once and it benefits the entire Home Assistant and GitHub community.

Thanks, I look forward to checking this PR again soon! :heart:

**Comment by robbiet480** [comment]
lol

**Comment by robbiet480** [comment]
1.5.1 is finally out the door, so time to merge this bad boy into master!!!!

**Pull request merged**
